/// Official undergraduate majors (pregrados) at Universidad de los Andes.
/// Source: https://uniandes.edu.co/programas-academicos
/// Keep this list alphabetically sorted for easy lookup.
const List<String> uniAndesMajors = [
  'Administración de Empresas',
  'Antropología',
  'Arquitectura',
  'Arte',
  'Biología',
  'Ciencia Política',
  'Derecho',
  'Diseño',
  'Economía',
  'Filosofía',
  'Física',
  'Geografía',
  'Geología',
  'Historia',
  'Ingeniería Biomédica',
  'Ingeniería Civil',
  'Ingeniería de Sistemas y Computación',
  'Ingeniería Eléctrica',
  'Ingeniería Electrónica',
  'Ingeniería Industrial',
  'Ingeniería Mecánica',
  'Ingeniería Química',
  'Literatura',
  'Matemáticas',
  'Medicina',
  'Música',
  'Psicología',
  'Química',
  'Sociología',
];
